data:
  identifier: mathematical_functions_schema.parallel_composed_function
  localized_concepts:
    eng: 985f7dcd-e3b5-59ae-8112-a1ea76e57fed
  domains:
    - concept_id: section-mathematical_functions_schema
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:mathematical_functions_schema
      ref_type: section
id: mathematical_functions_schema.parallel_composed_function
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that represents the parallel composed function {{entity}}'
  notes:
    - content: This type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:mathematical_functions_schema.maths_function,maths_function}} and {{urn:iso:std:iso:10303:-2:ed-1:en:tech:iso13584_generic_expressions_schema.multiple_arity_generic_expression,multiple_arity_generic_expression}} represents the mathematical function which is the composition of a "final" function with a list of "preparatory" functions supplying its arguments.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:mathematical_functions_schema
          version: '4'
      type: authoritative
      id: mathematical_functions_schema
  terms:
    - type: expression
      normative_status: preferred
      designation: parallel_composed_function
  domain: 'resource: mathematical_functions_schema'
  language_code: eng
  annotations: []
id: 985f7dcd-e3b5-59ae-8112-a1ea76e57fed
