---
data:
  identifier: Product_breakdown_mim.breakdown_of
  localized_concepts:
    eng: 6ae7a572-5727-5d78-b9da-373d91fab76c
  domains:
  - concept_id: section-Product_breakdown_mim
    source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_breakdown_mim
    ref_type: section
id: Product_breakdown_mim.breakdown_of
schema_version: v3
---
data:
  definition:
  - content: "{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity
      data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_breakdown_mim.product_definition_relationship,product_definition_relationship}}
      that represents the breakdown of {{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity,entity}}"
  notes:
  - content: A **breakdown_of** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_definition_schema.product_definition_relationship,product_definition_relationship}}
      that implements the ARM concept of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_breakdown_arm.Breakdown_of,Breakdown_of}}.
  sources:
  - origin:
      ref:
        source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_breakdown_mim
        version: '4'
    type: authoritative
  terms:
  - type: expression
    normative_status: preferred
    designation: breakdown_of
  domain: 'application module: Product_breakdown_mim'
  language_code: eng
  annotations: []
id: 6ae7a572-5727-5d78-b9da-373d91fab76c