data:
  identifier: Production_rule_mim.fact_type
  localized_concepts:
    eng: faf85d27-e686-5a94-9b76-3e38c6faa42e
  domains:
    - concept_id: section-Production_rule_mim
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_mim
      ref_type: section
id: Production_rule_mim.fact_type
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_property_definition_schema.property_definition,property_definition}} that represents the fact type {{entity}}'
  notes:
    - content: An **fact_type** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_property_definition_schema.property_definition,property_definition}} that implements the ARM concept of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_arm.Fact_type,Fact_type}}.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_mim
          version: '5'
      type: authoritative
      id: Production_rule_mim
  terms:
    - type: expression
      normative_status: preferred
      designation: fact_type
  domain: 'application module: Production_rule_mim'
  language_code: eng
  annotations: []
id: faf85d27-e686-5a94-9b76-3e38c6faa42e
