data:
  identifier: Product_environment_observed_arm.Observed_environment_view_definition_relationship
  localized_concepts:
    eng: 5a7f31ea-8b26-5b09-9264-63761ce4ed63
  domains:
    - concept_id: section-Product_environment_observed_arm
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_environment_observed_arm
      ref_type: section
id: Product_environment_observed_arm.Observed_environment_view_definition_relationship
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_view_definition_relationship_arm.View_definition_relationship,View_definition_relationship}} that represents the observed environment view definition relationship {{entity}}'
  notes:
    - content: An **Observed_environment_view_definition_relationship** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_view_definition_relationship_arm.View_definition_relationship,View_definition_relationship}} that represents an association between two {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_environment_observed_arm.Observed_environment_view,Observed_environment_view}} objects.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_environment_observed_arm
          version: '4'
      type: authoritative
      id: Product_environment_observed_arm
  terms:
    - type: expression
      normative_status: preferred
      designation: Observed_environment_view_definition_relationship
  domain: 'application module: Product_environment_observed_arm'
  language_code: eng
  annotations: []
id: 5a7f31ea-8b26-5b09-9264-63761ce4ed63
