---
data:
  identifier: Production_rule_mim.row_value
  localized_concepts:
    eng: bd6f087b-4d97-5ab6-9e2d-9bdb323c9b24
  domains:
  - concept_id: section-Production_rule_mim
    source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_mim
    ref_type: section
id: Production_rule_mim.row_value
schema_version: v3
---
data:
  definition:
  - content: "{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity
      data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_mim.compound_representation_item,compound_representation_item}}
      that represents the row value {{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity,entity}}"
  notes:
  - content: An **row_value** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:representation_schema.compound_representation_item,compound_representation_item}}
      that implements the ARM concept of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_arm.Row_value,Row_value}}.
  sources:
  - origin:
      ref:
        source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Production_rule_mim
        version: '5'
    type: authoritative
  terms:
  - type: expression
    normative_status: preferred
    designation: row_value
  domain: 'application module: Production_rule_mim'
  language_code: eng
  annotations: []
id: bd6f087b-4d97-5ab6-9e2d-9bdb323c9b24