data:
  identifier: Product_data_quality_inspection_result_arm.Data_quality_report_measurement_association
  localized_concepts:
    eng: 71ee7f97-2c78-5892-857d-f4f295887f79
  domains:
    - concept_id: section-Product_data_quality_inspection_result_arm
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_data_quality_inspection_result_arm
      ref_type: section
id: Product_data_quality_inspection_result_arm.Data_quality_report_measurement_association
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that represents the data quality report measurement association {{entity}}'
  notes:
    - content: A **Data_quality_report_measurement_association** is the representation of the correspondence between a {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_data_quality_inspection_result_arm.Data_quality_inspection_report,Data_quality_inspection_report}} and the {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_data_quality_criteria_arm.Data_quality_measurement_requirement,Data_quality_measurement_requirement}} used for the inspection.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_data_quality_inspection_result_arm
          version: '2'
      type: authoritative
      id: Product_data_quality_inspection_result_arm
  terms:
    - type: expression
      normative_status: preferred
      designation: Data_quality_report_measurement_association
  domain: 'application module: Product_data_quality_inspection_result_arm'
  language_code: eng
  annotations: []
id: 71ee7f97-2c78-5892-857d-f4f295887f79
