---
data:
  identifier: product_analysis_schema.behavioural_decomposition_of_temporal_spatial_domain
  localized_concepts:
    eng: b5a1a4d3-6103-5f96-adeb-349862097ae3
  domains:
  - concept_id: section-product_analysis_schema
    source: urn:iso:std:iso:10303:-2:ed-1:en:tech:product_analysis_schema
    ref_type: section
id: product_analysis_schema.behavioural_decomposition_of_temporal_spatial_domain
schema_version: v3
---
data:
  definition:
  - content: "{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity
      data type}} that represents the behavioural decomposition of temporal spatial
      domain {{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity,entity}}"
  notes:
  - content: A {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_analysis_schema.behavioural_decomposition_of_temporal_spatial_domain,behavioural_decomposition_of_temporal_spatial_domain}}
      is a decomposition of a {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_analysis_schema.temporal_spatial_domain,temporal_spatial_domain}}
      into specifications for different behaviours.
  sources:
  - origin:
      ref:
        source: urn:iso:std:iso:10303:-2:ed-1:en:tech:product_analysis_schema
        version: '1'
    type: authoritative
  terms:
  - type: expression
    normative_status: preferred
    designation: behavioural_decomposition_of_temporal_spatial_domain
  domain: 'resource: product_analysis_schema'
  language_code: eng
  annotations: []
id: b5a1a4d3-6103-5f96-adeb-349862097ae3