data:
  identifier: Product_class_mim.exclusive_product_concept_feature_category
  localized_concepts:
    eng: 19004fe5-3306-53e3-a90c-499f2b4b72ff
  domains:
    - concept_id: section-Product_class_mim
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_class_mim
      ref_type: section
id: Product_class_mim.exclusive_product_concept_feature_category
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_class_mim.product_concept_feature_category,product_concept_feature_category}} that represents the exclusive product concept feature category {{entity}}'
  notes:
    - content: An **exclusive_product_concept_feature_category** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_class_mim.product_concept_feature_category,product_concept_feature_category}} the members of which describe mutually exclusive characteristics of a product.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_class_mim
          version: '6'
      type: authoritative
      id: Product_class_mim
  terms:
    - type: expression
      normative_status: preferred
      designation: exclusive_product_concept_feature_category
  domain: 'application module: Product_class_mim'
  language_code: eng
  annotations: []
id: 19004fe5-3306-53e3-a90c-499f2b4b72ff
