data:
  identifier: Product_occurrence_arm.Quantified_instance
  localized_concepts:
    eng: d0f4c535-19c4-5c17-8e6b-6b750a5a6503
  domains:
    - concept_id: section-Product_occurrence_arm
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_occurrence_arm
      ref_type: section
id: Product_occurrence_arm.Quantified_instance
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_occurrence_arm.Product_occurrence_with_quantity,Product_occurrence_with_quantity}} that represents the quantified instance {{entity}}'
  notes:
    - content: A **Quantified_instance** is a type of {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_occurrence_arm.Product_occurrence_with_quantity,Product_occurrence_with_quantity}} that identifies a quantified occurrence of a part, the occurrence quantity being defined by a {{urn:iso:std:iso:10303:-2:ed-1:en:tech:Value_with_unit_arm.Value_with_unit,Value_with_unit}}.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:Product_occurrence_arm
          version: '5'
      type: authoritative
      id: Product_occurrence_arm
  terms:
    - type: expression
      normative_status: preferred
      designation: Quantified_instance
  domain: 'application module: Product_occurrence_arm'
  language_code: eng
  annotations: []
id: d0f4c535-19c4-5c17-8e6b-6b750a5a6503
