data:
  identifier: product_property_definition_schema.characterized_object_relationship
  localized_concepts:
    eng: 8f41260f-f33f-53c5-a284-4e8357c75297
  domains:
    - concept_id: section-product_property_definition_schema
      source: urn:iso:std:iso:10303:-2:ed-1:en:tech:product_property_definition_schema
      ref_type: section
id: product_property_definition_schema.characterized_object_relationship
schema_version: v3
---
data:
  definition:
    - content: '{{urn:iso:std:iso:10303:-2:ed-1:en:term:express-language.entity_data_type,entity data type}} that represents the characterized object relationship {{entity}}'
  notes:
    - content: A **characterized_object_relationship** is a relationship between two instances of the entity data type {{urn:iso:std:iso:10303:-2:ed-1:en:tech:product_property_definition_schema.characterized_object,characterized_object}} and provides an identification and description of this relationship.
  sources:
    - origin:
        ref:
          source: urn:iso:std:iso:10303:-2:ed-1:en:tech:product_property_definition_schema
          version: '10'
      type: authoritative
      id: product_property_definition_schema
  terms:
    - type: expression
      normative_status: preferred
      designation: characterized_object_relationship
  domain: 'resource: product_property_definition_schema'
  language_code: eng
  annotations: []
id: 8f41260f-f33f-53c5-a284-4e8357c75297
