---
data:
  identifier: general.product_configuration_information
  localized_concepts:
    eng: 1e67a26e-6d22-5345-a802-e91124bfcd6c
  domains:
  - concept_id: section-general
    source: urn:iso:std:iso:10303:-2:ed-1:en
    ref_type: section
id: 02670e68-a7dc-52ed-a004-8288daf73492
schema_version: v3
---
data:
  definition:
  - content: combination of product definition and operational information
  terms:
  - type: expression
    normative_status: preferred
    designation: product configuration information
  language_code: eng
  annotations: []
id: 1e67a26e-6d22-5345-a802-e91124bfcd6c