---
data:
  identifier: general.application_programming_interface_signature
  localized_concepts:
    eng: '06586e42-0b9a-54a3-b95c-8f0b5fee9a3f'
  domains:
  - concept_id: section-general
    source: urn:iso:std:iso:10303:-2:ed-1:en
    ref_type: section
id: d8b96bbc-5a7b-5ded-b6a0-9c18b8c46ff4
schema_version: v3
---
data:
  definition:
  - content: description of the set of functions, protocols, and tools that programmers
      can use to enhance applications to access network services, devices, or operating
      systems
  terms:
  - type: expression
    normative_status: preferred
    designation: application programming interface signature
  - type: expression
    normative_status: admitted
    designation: APIS
  language_code: eng
  annotations: []
id: '06586e42-0b9a-54a3-b95c-8f0b5fee9a3f'