---
data:
  identifier: general.application_protocol
  localized_concepts:
    eng: 7e5e1b83-2020-548a-9544-d75cb62e7c58
  domains:
  - concept_id: section-general
    source: urn:iso:std:iso:10303:-2:ed-1:en
    ref_type: section
id: c6cbc5aa-a101-5585-a429-b3c43608ae60
schema_version: v3
---
data:
  definition:
  - content: part of ISO 10303 that specifies an application interpreted model or
      an application domain model satisfying the scope and information requirements
      for a specific application
  notes:
  - content: This definition differs from the definition used in <<ISO_7498-2_1989>>
      because the protocols address different contexts of use.
  terms:
  - type: expression
    normative_status: preferred
    designation: application protocol
  - type: expression
    normative_status: admitted
    designation: AP
  domain: ISO 10303
  language_code: eng
  annotations: []
id: 7e5e1b83-2020-548a-9544-d75cb62e7c58