---
data:
  identifier: general.application_activity_model
  localized_concepts:
    eng: 9bd809f8-9bf3-5484-a29d-d83adc18299c
  domains:
  - concept_id: section-general
    source: urn:iso:std:iso:10303:-2:ed-1:en
    ref_type: section
id: 9914f2bb-8f13-5a7e-8c95-b99d42682c18
schema_version: v3
---
data:
  definition:
  - content: model that describes an application in terms of its processes and information
      flows
  terms:
  - type: expression
    normative_status: preferred
    designation: application activity model
  - type: expression
    normative_status: admitted
    designation: AAM
  language_code: eng
  annotations: []
id: 9bd809f8-9bf3-5484-a29d-d83adc18299c